spring.application.name=room-service


# Server port for the RoomService
server.port=8086

# PostgreSQL database properties
spring.datasource.url=jdbc:postgresql://localhost:5432/roomservice_db
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
